import RamaLean
#print axioms AbelianCover.det_sub_smul_one_im
#print axioms AbelianCover.exists_zero_of_integral_zero
#print axioms AbelianCover.reduction
#print axioms AbelianCover.root_mem_of_average
#print axioms AdjugatePSD.adjugate_posDef
#print axioms BandLipschitz.grad_l1_bound
#print axioms BandLipschitz.quad_form_bound
#print axioms BandLipschitz.sum_deg_bound
#print axioms BandTheorem.band_of
#print axioms BandTheorem.conj10_of_bands_subset
#print axioms BandTheorem.countAbove_eq_countBands
#print axioms BandTheorem.mem_of_squeezed
#print axioms BandTheorem.ordConnected_range_of_continuous
#print axioms BipartiteMatchingPoly.alt_sum_conflictPairs
#print axioms BipartiteMatchingPoly.bipQ_delete_left
#print axioms BipartiteMatchingPoly.card_powersetCard_filter_superset
#print axioms BipartiteMatchingPoly.conflict_degree
#print axioms BipartiteMatchingPoly.four_cycle_trichotomy
#print axioms BipartiteMatchingPoly.mCount_closed_form
#print axioms BipartiteMatchingPoly.mCount_eq_sum_alt
#print axioms BipartiteMatchingPoly.mCount_grouped
#print axioms BipartiteMatchingPoly.mCount_grouped_range
#print axioms BipartiteMatchingPoly.mCount_inclusion_exclusion
#print axioms BipartiteMatchingPoly.mCount_one_via_inclusion_exclusion
#print axioms BipartiteMatchingPoly.powerset_conflictPairs_eq
#print axioms BipartiteMatchingPoly.taylor_coeff_of_natDegree_le
#print axioms BipartiteMatchingPoly.three_meeting_share
#print axioms BiregularBlocking.biregular_reduction
#print axioms BiregularBlocking.branch_root_sep
#print axioms BiregularBlocking.no_tree_of_two_le_degree
#print axioms Cavity.cavity_step
#print axioms CavityThreshold.cavity_step_deficient
#print axioms CavityThreshold.compression_sum
#print axioms CavityThreshold.double_root_at_threshold
#print axioms CavityThreshold.inv_one_sub_sub_one_add
#print axioms CavityThreshold.km_satisfies_target
#print axioms CavityThreshold.km_slack_calc
#print axioms CavityThreshold.no_slack_propagates
#print axioms CavityThreshold.one_add_le_inv_one_sub
#print axioms CavityThreshold.ratio_form
#print axioms CavityThreshold.remainder_upper
#print axioms CavityThreshold.threshold_iff
#print axioms CavityThreshold.trace_le_of_rayleigh
#print axioms CompleteBipartiteMargin.abs_eigenvalue_le_max_rowsum
#print axioms CompleteBipartiteMargin.margin_pos_of_rowsum
#print axioms CompleteBipartiteMargin.no_root_below_gap_edge
#print axioms CotreeCycle.disjoint_edges_of_disjoint_support
#print axioms CotreeCycle.exists_cotree_edge
#print axioms CrossTerm.crossTerm_eq_sq
#print axioms CrossTerm.crossTerm_eq_sq_sub
#print axioms CrossTerm.crossTerm_eq_zero_iff
#print axioms CrossTerm.crossTerm_nonneg
#print axioms CrossTerm.sum_gram_prod_eq_sum_sq
#print axioms CrossingSplit.crit_of_ratio
#print axioms CrossingSplit.ne_zero_of_split
#print axioms CutVertexMechanism.branch_factor
#print axioms CutVertexMechanism.root_of_branch_factor
#print axioms DefectLocalization.conj10_of_zero_defect
#print axioms DefectLocalization.root_free_core
#print axioms DefectLocalization.thickening_zero
#print axioms DefectLocalization.zeros_subset_thickening
#print axioms FeedbackGapCount.conj10_fvs_one_of
#print axioms FeedbackGapCount.gapcount_fvs_one_of
#print axioms FeedbackTwo.eq_of_window3
#print axioms FeedbackTwo.gapcount_fvs_two_sign
#print axioms FeedbackVertex.feedback_one_of
#print axioms FeedbackVertex.matching_ratio
#print axioms FeedbackVertex.no_bypass
#print axioms FeedbackVertex.resolvent_diag
#print axioms FeedbackVertex.trace_ne_zero_of_definite
#print axioms GramDet.border_det_eq_zero_of_mem_span
#print axioms GramDet.border_gram
#print axioms GramDet.det_border
#print axioms GramDet.det_gram_eq_zero_of_dep
#print axioms GramDet.gram_det_basis_of_injective
#print axioms GramDet.gram_det_basis_of_not_injective
#print axioms GramDet.hsimple_of_border_zero
#print axioms GramDet.hsimple_of_mem_span
#print axioms HallCounterexample.muG_eq
#print axioms HallCounterexample.muG_root_simple
#print axioms HallCounterexample.muG_root_sqrt5
#print axioms KestenMcKay.G_at_edge
#print axioms KestenMcKay.excess_eq
#print axioms KestenMcKay.excess_lt
#print axioms KestenMcKay.excess_pos
#print axioms KestenMcKay.inv_G_div_edge
#print axioms KestenMcKay.radical_at_edge
#print axioms LaguerreBand.band_endpoints
#print axioms LaguerreBand.laguerre_band
#print axioms LaguerreBand.lastRow_le
#print axioms LaguerreBand.rowRadius_le
#print axioms LaguerreBand.sqrt_amgm
#print axioms LaguerreBand.sqrt_step
#print axioms MinimumDegreeThreshold.C2_of_D3
#print axioms MinimumDegreeThreshold.conj10_of_regular
#print axioms MinimumDegreeThreshold.threshold_is_three
#print axioms MomentLadder.band_of_all_moments
#print axioms MomentLadder.le_of_power_sum_le
#print axioms MomentLadder.rate_lt_target
#print axioms MomentLadder.reach_of_moment
#print axioms MomentLadder.reach_trivial_of_rate
#print axioms MomentLadder.reach_unbounded
#print axioms MomentLadder.reach_unbounded_of_rate
#print axioms MomentTransfer.edge_gap_pos
#print axioms MomentTransfer.geom_remainder
#print axioms MomentTransfer.inv_close
#print axioms MomentTransfer.remainder_le
#print axioms MomentTransfer.stieltjes_close
#print axioms Paper2.cG_factored
#print axioms Paper2.expFormula
#print axioms Paper2.quotient_parity
#print axioms Paper2.thm1_Sr
#print axioms Paper2FibLucas.cor2_phi3_general
#print axioms Paper2FibLucas.fib_shift
#print axioms Paper2GenFun.genPhi_mul
#print axioms Paper2GenFun.genU_mul
#print axioms Paper2Roots.Phi_ne_zero_of_two_lt_abs
#print axioms Paper2Roots.one_lt_abs_cT
#print axioms Paper2Unicyclic.cU_ne_zero_of_one_le_abs
#print axioms Paper2Unicyclic.cV_root_mem_band
#print axioms Paper2Unicyclic.gap_edge_identity
#print axioms Paper2Unicyclic.gap_eq_zero_iff
#print axioms Paper2Unicyclic.region_closure_bound
#print axioms Paper2Unicyclic.subdivision_gap
#print axioms ParitySplit.mean_mem_Icc
#print axioms ParitySplit.ne_zero_iff_ne_weighted_mean
#print axioms ParitySplit.ne_zero_of_outside_band
#print axioms ParitySplit.zero_iff_weighted_mean
#print axioms PathCount.alt_count
#print axioms PathCount.alt_count_last
#print axioms PathCount.blocked_le_left
#print axioms PathCount.unblocked_le
#print axioms PathTreeInduction.invariant
#print axioms PathTreeInduction.invariant_depth
#print axioms PathTreeInduction.no_vanishing
#print axioms PathTreeInduction.saturation_blocks_improvement
#print axioms PathTreeRoute.conj_of_pathtree
#print axioms PathTreeRoute.pathtree_fails_of_violation
#print axioms Plucker.crossTerm_nonneg_plucker
#print axioms Plucker.hsimple_of_comb
#print axioms Plucker.iota_eq_comb
#print axioms Plucker.pl_dot
#print axioms PowerSumCertificate.roots_ge_of_powersum
#print axioms ProductBound.band_iff_pi
#print axioms ProductBound.edge_gap
#print axioms ProductBound.edge_gap_eq_zero_iff
#print axioms ProductBound.no_root_above
#print axioms ProductBound.target_le_xxz
#print axioms ProductBound.weak_beats_ab
#print axioms ProductBound.weak_beats_mp
#print axioms ProductBound.weak_bound
#print axioms ProductBound.xxz_eq_ab_iff
#print axioms ProductBound.xxz_le_ab
#print axioms RatioCertificate.decay
#print axioms RatioCertificate.decay_lt_one
#print axioms RatioCertificate.decay_nonneg
#print axioms RatioCertificate.spec_excluded
#print axioms RatioRoute.closure_iff
#print axioms RatioRoute.induction_step
#print axioms RatioRoute.left_step
#print axioms RatioRoute.refined_weaker
#print axioms RatioRoute.right_step
#print axioms RatioRoute.right_step_bound
#print axioms RatioRoute.right_step_refined
#print axioms RatioRoute.right_step_sharp
#print axioms RatioRoute.structural_closure
#print axioms RootSeparation.cauchy_lower
#print axioms RootSeparation.matching_root_sep
#print axioms RootSeparation.sfm_of_separation
#print axioms SeparationOrder.cutBracket_natDegree
#print axioms SeparationOrder.freedom_grows
#print axioms SeparationOrder.root_of_two_cut
#print axioms SeparationOrder.twoCutBracket_natDegree
#print axioms SeparationOrder.two_cut_factor
#print axioms ShellBound.abs_mul_eq_max_mul_min
#print axioms ShellBound.det_le_on_shell
#print axioms ShellBound.integral_le_three_halves
#print axioms ShellBound.reach_le_sqrt
#print axioms SignReflection.band_edges_swap
#print axioms SignReflection.mixedChar_reflect
#print axioms SignReflection.sign_avg_reflect
#print axioms SignReflection.sum_multiaffine
#print axioms SignReflection.sum_prod_sgn
#print axioms SoftEdge.discriminant_factors
#print axioms SoftEdge.edge_scale
#print axioms SoftEdge.edge_unimprovable
#print axioms SoftEdge.exponent_floor
#print axioms SoftEdge.inf_not_attained
#print axioms SoftEdge.inner_edge_simple
#print axioms SoftEdge.no_uniform_lower_bound
#print axioms SoftEdge.rayleigh_between
#print axioms SoftEdge.rayleigh_in_gap
#print axioms SoftEdge.sqrt_edge_exponent
#print axioms SoftEdge.sqrt_edge_quantile
#print axioms SubcubicCounterexample.degree_A3
#print axioms SubcubicCounterexample.quartic_dvd_A3
#print axioms SubcubicCounterexample.quartic_factor
#print axioms Tightness.adj_compressed
#print axioms Tightness.crossTerm_nonneg_of_tight
#print axioms Tightness.iota_antisymm
#print axioms Tightness.iota_proj_of_orthogonal
#print axioms Tightness.iota_split
#print axioms Tightness.tight_sum_contraction_eq_zero
#print axioms TorusGodsilGutman.mu_ne_zero_of_nonvanishing
#print axioms TorusGodsilGutman.nonvanishing_average_ne_zero
#print axioms TorusGodsilGutman.sign_const_of_nonvanishing
#print axioms TorusGodsilGutman.sum_ne_zero_of_disjoint_support
#print axioms TracePSD.sq_sum_sub_sum_sq
#print axioms TracePSD.sum_sq_le_sq_sum
#print axioms TracePSD.trace_sq_le_sq_trace
#print axioms TreeSubstitution.homogenize
#print axioms TreeSubstitution.star_ratio
#print axioms TreeSubstitution.subdivision_abs
#print axioms TreeSubstitution.subdivision_root
#print axioms VertexSplit.det_add_vecMulVec
#print axioms VertexSplit.det_le_det_add_vecMulVec
#print axioms WeightBound.crit_of_band_geometry
#print axioms WeightBound.factor_above
#print axioms WeightBound.factor_below
#print axioms XuAdditiveProduct.xu_conj21_false
#print axioms XuAdditiveProduct.xu_conj24_false
#print axioms XuAdditiveProduct.xu_dichotomy_second_branch
#print axioms XuBound.xu_lt_note_target
#print axioms XuSharp.bridge_roots
#print axioms XuSharp.no_smaller_constant
#print axioms XuSharp.sharp_of_ladder