"""Item 2: is K_{d,q} the extremal case among (d,q)-biregular graphs?

For K_{d,q} the margin x_min - g is proved positive, tending to sqrt(d-1) - h_d/2 with h_d the
largest zero of He_d (RamaLean/CompleteBipartiteMargin.lean). The question that decides whether
that proof extends to Song-Fan-Miao Problem 1 is whether the complete bipartite graph MINIMISES
the margin among all (d,q)-biregular graphs. If it does, the proved bound covers the family. If
some other biregular graph dips lower, that graph is where Problem 1 is decided.

FROZEN BEFORE THE DATA:
  P2. Among connected (d,q)-biregular graphs, K_{d,q} has the smallest margin.

g = sqrt(q-1) - sqrt(d-1) is the gap edge of the (d,q)-biregular tree; x_min is the smallest
positive root of mu_G, by memoised vertex deletion. Graphs are generated by random bipartite
degree-constrained matching, rejected unless simple, connected and exactly biregular.
"""
import os, sys, math, time, random, functools
for _v in ('OMP_NUM_THREADS','OPENBLAS_NUM_THREADS','MKL_NUM_THREADS'): os.environ[_v]='2'
import sympy as sp
x = sp.Symbol('x')

def rand_biregular(d, q, r, seed):
    """r right vertices of degree q, m=r*q/d left of degree d."""
    if (r*q) % d: return None
    m = (r*q)//d
    rng = random.Random(seed)
    for _ in range(400):
        stubs = [j for j in range(r) for _ in range(q)]
        rng.shuffle(stubs)
        adj = [set() for _ in range(m)]
        ok = True
        for i in range(m):
            take = stubs[i*d:(i+1)*d]
            if len(set(take)) != d: ok = False; break
            adj[i] = set(take)
        if not ok: continue
        deg = [0]*r
        for i in range(m):
            for j in adj[i]: deg[j]+=1
        if any(t != q for t in deg): continue
        edges = [(i, m+j) for i in range(m) for j in adj[i]]
        n = m+r
        A = {i:set() for i in range(n)}
        for a,b in edges: A[a].add(b); A[b].add(a)
        st,vis=[0],{0}
        while st:
            u=st.pop()
            for w in A[u]:
                if w not in vis: vis.add(w); st.append(w)
        if len(vis)==n: return n, edges
    return None

def complete_bip(d,q):
    return d+q, [(i, d+j) for i in range(d) for j in range(q)]

def mu_memo(n, edges):
    adj={i:set() for i in range(n)}
    for a,b in edges: adj[a].add(b); adj[b].add(a)
    sys.setrecursionlimit(300000)
    @functools.lru_cache(maxsize=None)
    def rec(vs):
        S=set(vs)
        if not S: return sp.Integer(1)
        v=min(S,key=lambda z: len(adj[z]&S)); S1=S-{v}
        t=x*rec(tuple(sorted(S1)))
        for u in adj[v]&S: t-=rec(tuple(sorted(S1-{u})))
        return sp.expand(t)
    return rec(tuple(range(n)))

def xmin_of(n, edges):
    co=sp.Poly(mu_memo(n,edges),x).all_coeffs()
    while co and co[-1]==0: co.pop()
    if len(co)<2: return None
    try:
        rs=sorted(float(sp.re(r)) for r in sp.Poly(co,x).nroots(n=25,maxsteps=5000)
                  if abs(sp.im(r))<1e-12 and sp.re(r)>1e-9)
    except Exception: return None
    return rs[0] if rs else None

def main():
    print("P2 (frozen): K_{d,q} minimises the margin among (d,q)-biregular graphs.\n")
    print(f"{'d':>3}{'q':>4}{'graph':>16}{'n':>5}{'gap edge':>10}{'x_min':>11}"
          f"{'margin':>10}{'vs K':>10}")
    t0=time.time(); viol=[]
    for d in (3,4,5):
        for q in (6,8,9,10,12):
            nk,ek = complete_bip(d,q)
            xk = xmin_of(nk,ek)
            if xk is None: continue
            g = math.sqrt(q-1)-math.sqrt(d-1)
            mk = xk-g
            print(f"{d:>3}{q:>4}{'K_{d,q}':>16}{nk:>5}{g:>10.5f}{xk:>11.6f}{mk:>10.5f}{'--':>10}")
            for r in (4,5,6,7):
                if time.time()-t0>1500: break
                got=0
                for seed in range(6):
                    R = rand_biregular(d,q,r,seed)
                    if R is None: continue
                    n,edges = R
                    if n>34 or n==nk: continue
                    xm = xmin_of(n,edges)
                    if xm is None: continue
                    got+=1
                    m = xm-g
                    flag = "  BELOW K" if m < mk-1e-9 else ""
                    print(f"{d:>3}{q:>4}{f'rand r={r} s={seed}':>16}{n:>5}{g:>10.5f}"
                          f"{xm:>11.6f}{m:>10.5f}{m-mk:>10.5f}{flag}", flush=True)
                    if m < mk-1e-9: viol.append((d,q,r,seed,n,m,mk))
                    if got>=2: break
            print()
    print(f"{time.time()-t0:.0f}s")
    if viol:
        print(f"P2 IS FALSE: {len(viol)} biregular graphs with a SMALLER margin than K_"+"{d,q}.")
        for v in sorted(viol,key=lambda t:t[5])[:6]:
            print(f"  d={v[0]} q={v[1]} r={v[2]} n={v[4]} margin={v[5]:.5f} vs K {v[6]:.5f}")
        print("  Those are where Song-Fan-Miao Problem 1 is decided.")
    else:
        print("P2 holds on this sample: K_{d,q} is extremal, so the proved bound covers the "
              "family here.")
if __name__=='__main__': sys.exit(main())
