"""Is the commuting family the largest in its class? The direct search behind A9.

Conjecture 1.4 restricted to the commuting locus is a theorem (Corollary 36 of the note) and the
constant there is attained. What remains is whether the commuting locus is EXTREMAL: whether the
greatest root over all tight rank-b projection families is attained on it. If it is, the general
conjecture follows from the commuting case.

This searches directly. At each commuting family, many random tight projection families with the
same (p, q, a, b) are generated by alternating projection and their greatest roots compared with
the commuting one. A random family exceeding it would refute the extremality and with it the
reduction; none has.

FROZEN BEFORE THE DATA:
  P39. At every commuting family tested, no random tight projection family with the same
       parameters has a greater root.

The complementary direction is \\S rank of the note: across the rank-n interpolation
A_k = (b/n) Q_k, the projections are the variance-minimizing end and the scalar family (b/p)I the
Poisson end, and the greatest root increases away from the projections. So the projections are the
smallest across ranks and, on this evidence, the commuting ones the largest within the projection
class. That conjunction is what the conjecture needs, and neither half is proved here.

The rank hypothesis matters and is easy to state wrongly: (b/p)I has rank p, not b, so it shows
that trace and tightness do not suffice, not that a rank-b hypothesis fails.
"""

import os
for _v in ('OMP_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'MKL_NUM_THREADS'):
    os.environ[_v] = '2'

import sys
import math
import time
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__))
                 if '__file__' in globals() else 'code')
import quickmode
from mixed_char_poly import mixed_char_poly
from tff import build_tff
from hessian import coord_family

QUICK = quickmode.QUICK


def ymax(A):
    r = np.roots(mixed_char_poly(A))
    re = [z.real for z in r if abs(z.imag) < 1e-7]
    return max(re) if re else float('nan')


def cyc(m):
    return m, [[i, (i + 1) % m] for i in range(m)]


def cube8():
    return 8, [[0, 1], [1, 2], [2, 3], [3, 0], [4, 5], [5, 6], [6, 7], [7, 4],
               [0, 4], [1, 5], [2, 6], [3, 7]]


def K33():
    return 6, [[i, 3 + j] for i in range(3) for j in range(3)]


def main():
    t0 = time.time()
    print("P39 (frozen): no random tight projection family exceeds the commuting one at the same")
    print("(p, q, a, b).\n")
    rng = np.random.default_rng(20260906)
    ntry = 8 if QUICK else 40
    fams = [("C_4", 2, 2, cyc(4)), ("C_6", 2, 2, cyc(6))]
    if not QUICK:
        fams += [("K_{3,3}", 3, 2, K33()), ("cube", 3, 2, cube8())]
    print(f"{'family':>10}{'(a,b)':>8}{'p':>4}{'q':>4}{'band edge':>11}{'commuting':>12}"
          f"{'best random':>13}{'gap':>11}{'tried':>7}")
    beaten = 0
    for (nm, a, b, (p, lines)) in fams:
        if time.time() - t0 > (25.0 if QUICK else 600.0):
            print("  [budget reached]"); break
        q = len(lines)
        yc = ymax(coord_family(p, lines))
        best, nb = -1.0, 0
        for _ in range(ntry):
            A, res = build_tff(p, q, a, b, rng)
            if res > 1e-9:
                continue
            nb += 1
            best = max(best, ymax(A))
        if yc < best - 1e-9:
            beaten += 1
        edge = (math.sqrt(a - 1) + math.sqrt(b - 1)) ** 2
        print(f"{nm:>10}{f'({a},{b})':>8}{p:>4}{q:>4}{edge:>11.4f}{yc:>12.6f}{best:>13.6f}"
              f"{yc - best:>+11.6f}{nb:>7}")
    print(f"\n  commuting families beaten: {beaten}")
    if beaten:
        print("  P39 IS FALSE and the reduction of Conjecture 1.4 to the commuting case fails.")
    else:
        print("  P39 holds where tested. That is evidence for the extremality, not a proof, and")
        print("  the search is random rather than adversarial: it samples the class, it does not")
        print("  attack the statement.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
