import RamaLean.Paper3FourDivides
import RamaLean.OrbitSumDivisibility
/-!
# `8 ∣ a(n)` for `n ≥ 17` (Klein-four extension of the involution)

Rows `m` with all prime factors `≡ 1 (mod 4)` are `≡ (1,…,1) (mod 4)`; the regular
`(ℤ/2)²` (Klein-four `V₄`) action on four such rows (`m = 1,5,13,17`) — generated by the
double transpositions `(c₀c₁)(c₂c₃)` and `(c₀c₂)(c₁c₃)` — is by even permutations, acts
freely on the sign-`(−1)` terms (any nontrivial element moves `c₀`), and preserves
`∏ gcd (mod 4)`. Via the orbit-sum engine `sum_zmod_eq_zero_of_free_invariant`, this forces
`4 ∣ Σ`, hence (with `8 ∣ det`) `8 ∣ a(n)`. The two generators are not disjoint, so `Commute`
is obtained from `perm_conj_swap` (`e·(a b)·e⁻¹ = (e a)(e b)`). Standard axioms, no `sorry`.
-/
open Matrix Equiv Finset
namespace Paper3Four

/-- An involution `a` (`a² = 1`) as a monoid hom `Multiplicative (ZMod 2) →* G`. -/
def involHom {G : Type*} [Group G] (a : G) (ha : a ^ 2 = 1) :
    Multiplicative (ZMod 2) →* G :=
  MonoidHom.mk' (fun x => a ^ ((Multiplicative.toAdd x).val)) (by
    intro x y
    show a ^ ((Multiplicative.toAdd (x * y)).val)
      = a ^ ((Multiplicative.toAdd x).val) * a ^ ((Multiplicative.toAdd y).val)
    have key : ∀ m : ℕ, a ^ m = a ^ (m % 2) := fun m => by
      conv_lhs => rw [← Nat.div_add_mod m 2, pow_add, pow_mul, ha, one_pow, one_mul]
    rw [toAdd_mul, ← pow_add, key ((Multiplicative.toAdd x + Multiplicative.toAdd y).val),
        key ((Multiplicative.toAdd x).val + (Multiplicative.toAdd y).val)]
    congr 1
    rw [ZMod.val_add]; omega)

lemma involHom_apply {G : Type*} [Group G] (a : G) (ha : a ^ 2 = 1)
    (m : Multiplicative (ZMod 2)) : involHom a ha m = a ^ ((Multiplicative.toAdd m).val) := rfl

/-- Number-theoretic input: if every divisor of `m` is `≡ 1 (mod 4)` then
`gcd(m,k) ≡ 1 (mod 4)`. -/
lemma gcd_mod4_one (m k : ℕ) (hm0 : m ≠ 0) (hdiv : ∀ d ∈ m.divisors, (d : ZMod 4) = 1) :
    (Nat.gcd m k : ZMod 4) = 1 :=
  hdiv _ (Nat.mem_divisors.mpr ⟨Nat.gcd_dvd_left m k, hm0⟩)

variable {α : Type*} [DecidableEq α]

lemma disjoint_swap_swap {p q r s : α}
    (hpr : p ≠ r) (hps : p ≠ s) (hqr : q ≠ r) (hqs : q ≠ s) :
    (swap p q).Disjoint (swap r s) := by
  intro x
  by_cases hp : x = p
  · right; rw [hp, swap_apply_of_ne_of_ne hpr hps]
  by_cases hq : x = q
  · right; rw [hq, swap_apply_of_ne_of_ne hqr hqs]
  · left; exact swap_apply_of_ne_of_ne hp hq

lemma sq_eq_one_of_disjoint {p q r s : α}
    (hd : (swap p q).Disjoint (swap r s)) : (swap p q * swap r s) ^ 2 = 1 := by
  have hc := hd.commute
  rw [sq]
  calc swap p q * swap r s * (swap p q * swap r s)
      = swap p q * (swap r s * swap p q) * swap r s := by group
    _ = swap p q * (swap p q * swap r s) * swap r s := by rw [hc.eq]
    _ = swap p q * swap p q * (swap r s * swap r s) := by group
    _ = 1 := by rw [Equiv.swap_mul_self, Equiv.swap_mul_self, mul_one]

lemma dt_fix {p q r s x : α} (hp : x ≠ p) (hq : x ≠ q) (hr : x ≠ r) (hs : x ≠ s) :
    (swap p q * swap r s) x = x := by
  rw [Perm.mul_apply, swap_apply_of_ne_of_ne hr hs, swap_apply_of_ne_of_ne hp hq]

/-- If `a z = z` then `aᵏ z = z`. -/
lemma powFix {a : Perm α} {z : α} (h : a z = z) : ∀ k, (a ^ k) z = z
  | 0 => rfl
  | (k + 1) => by rw [pow_succ, Perm.mul_apply, h]; exact powFix h k

/-- Conjugating a transposition by any permutation relabels its two points. -/
lemma perm_conj_swap (e : Perm α) (a b : α) :
    e * swap a b * e⁻¹ = swap (e a) (e b) := by
  ext x
  simp only [Perm.mul_apply, swap_apply_def, Perm.inv_def, Equiv.symm_apply_eq,
    apply_ite e, Equiv.apply_symm_apply]

/-- `8 ∣ det(gcd matrix)` for `n ≥ 5`, since `φ(3)·φ(5) = 2·4 = 8`. -/
lemma eight_dvd_gcd_det (n : ℕ) (hn : 5 ≤ n) : (8 : ℤ) ∣ (gcdMat n).det := by
  rw [gcd_det]
  have h2mem : (⟨2, by omega⟩ : Fin n) ∈ (Finset.univ : Finset (Fin n)) := Finset.mem_univ _
  have h4mem : (⟨4, by omega⟩ : Fin n) ∈ (Finset.univ.erase (⟨2, by omega⟩ : Fin n)) := by
    rw [Finset.mem_erase]; exact ⟨by simp [Fin.ext_iff], Finset.mem_univ _⟩
  rw [← Finset.mul_prod_erase _ _ h2mem, ← Finset.mul_prod_erase _ _ h4mem]
  have e2 : (Nat.totient (((⟨2, by omega⟩ : Fin n) : ℕ) + 1) : ℤ) = 2 := by
    show (Nat.totient (2 + 1) : ℤ) = 2; decide
  have e4 : (Nat.totient (((⟨4, by omega⟩ : Fin n) : ℕ) + 1) : ℤ) = 4 := by
    show (Nat.totient (4 + 1) : ℤ) = 4; decide
  rw [e2, e4]; exact ⟨_, by ring⟩

/-- The Klein four-group `(ℤ/2)²`, as a product of two `Multiplicative (ZMod 2)`.
Defined as a reducible `abbrev` so the `Fintype`/`Group` instances are found
without a diamond (a `set`/`let`-bound local would break instance resolution). -/
abbrev KleinG : Type := Multiplicative (ZMod 2) × Multiplicative (ZMod 2)

/-- **Theorem (`8 ∣ a(n)` for `n ≥ 17`).**  Regular Klein-four `V₄` on four rows
`m = 1,5,13,17` (values `0,4,12,16`), all `≡ 1 (mod 4)`. -/
theorem eight_dvd_permanent (n : ℕ) (hn : 17 ≤ n) : (8 : ℤ) ∣ (gcdMat n).permanent := by
  set c0 : Fin n := ⟨0, by omega⟩ with hcv0
  set c1 : Fin n := ⟨4, by omega⟩ with hcv1
  set c2 : Fin n := ⟨12, by omega⟩ with hcv2
  set c3 : Fin n := ⟨16, by omega⟩ with hcv3
  set S : Finset (Fin n) := {c0, c1, c2, c3} with hS
  have v0 : (c0:ℕ) = 0 := by rw [hcv0]
  have v1 : (c1:ℕ) = 4 := by rw [hcv1]
  have v2 : (c2:ℕ) = 12 := by rw [hcv2]
  have v3 : (c3:ℕ) = 16 := by rw [hcv3]
  have h01 : c0 ≠ c1 := Fin.ne_of_val_ne (by simp only [v0,v1,v2,v3]; omega)
  have h02 : c0 ≠ c2 := Fin.ne_of_val_ne (by simp only [v0,v1,v2,v3]; omega)
  have h03 : c0 ≠ c3 := Fin.ne_of_val_ne (by simp only [v0,v1,v2,v3]; omega)
  have h12 : c1 ≠ c2 := Fin.ne_of_val_ne (by simp only [v0,v1,v2,v3]; omega)
  have h13 : c1 ≠ c3 := Fin.ne_of_val_ne (by simp only [v0,v1,v2,v3]; omega)
  have h23 : c2 ≠ c3 := Fin.ne_of_val_ne (by simp only [v0,v1,v2,v3]; omega)
  set a : Perm (Fin n) := swap c0 c1 * swap c2 c3 with ha_def
  set b : Perm (Fin n) := swap c0 c2 * swap c1 c3 with hb_def
  have ha2 : a ^ 2 = 1 := sq_eq_one_of_disjoint (disjoint_swap_swap h02 h03 h12 h13)
  have hb2 : b ^ 2 = 1 := sq_eq_one_of_disjoint (disjoint_swap_swap h01 h03 h12.symm h23)
  have hac0 : a c0 = c1 := by
    rw [ha_def, Perm.mul_apply, swap_apply_of_ne_of_ne h02 h03, swap_apply_left]
  have hac1 : a c1 = c0 := by
    rw [ha_def, Perm.mul_apply, swap_apply_of_ne_of_ne h12 h13, swap_apply_right]
  have hac2 : a c2 = c3 := by
    rw [ha_def, Perm.mul_apply, swap_apply_left, swap_apply_of_ne_of_ne h03.symm h13.symm]
  have hac3 : a c3 = c2 := by
    rw [ha_def, Perm.mul_apply, swap_apply_right, swap_apply_of_ne_of_ne h02.symm h12.symm]
  have hbc0 : b c0 = c2 := by
    rw [hb_def, Perm.mul_apply, swap_apply_of_ne_of_ne h01 h03, swap_apply_left]
  -- Commute a b  via  a b a⁻¹ = b
  have hconj : a * b * a⁻¹ = b := by
    rw [hb_def, show a * (swap c0 c2 * swap c1 c3) * a⁻¹
          = (a * swap c0 c2 * a⁻¹) * (a * swap c1 c3 * a⁻¹) from by group,
      perm_conj_swap, perm_conj_swap, hac0, hac2, hac1, hac3]
    exact (disjoint_swap_swap h01.symm h12 h03.symm h23.symm).commute.eq
  have hab_comm : Commute a b := mul_inv_eq_iff_eq_mul.mp hconj
  have hsa : Perm.sign a = 1 := by rw [ha_def, map_mul, Perm.sign_swap h01, Perm.sign_swap h23]; decide
  have hsb : Perm.sign b = 1 := by rw [hb_def, map_mul, Perm.sign_swap h02, Perm.sign_swap h13]; decide
  set φ : KleinG →* Perm (Fin n) :=
    MonoidHom.noncommCoprod (involHom a ha2) (involHom b hb2) (fun m k => by
      rw [involHom_apply, involHom_apply]; exact hab_comm.pow_pow _ _) with hφ
  have hφfix : ∀ (g : KleinG) (z : Fin n), z ∉ S → φ g z = z := by
    intro g z hz
    simp only [hS, Finset.mem_insert, Finset.mem_singleton, not_or] at hz
    have hza : a z = z := by rw [ha_def]; apply dt_fix <;> tauto
    have hzb : b z = z := by rw [hb_def]; apply dt_fix <;> tauto
    rw [hφ, MonoidHom.noncommCoprod_apply, Perm.mul_apply, involHom_apply, involHom_apply,
      powFix hzb, powFix hza]
  have hφinj : Function.Injective φ := by
    rw [← MonoidHom.ker_eq_bot_iff, eq_bot_iff]; intro g hg
    rw [MonoidHom.mem_ker] at hg
    have h0 : φ g c0 = c0 := by rw [hg]; rfl
    rw [hφ, MonoidHom.noncommCoprod_apply, Perm.mul_apply, involHom_apply, involHom_apply] at h0
    have hs2 : (Multiplicative.toAdd g.1).val = 0 ∨ (Multiplicative.toAdd g.1).val = 1 := by
      have := ZMod.val_lt (Multiplicative.toAdd g.1); omega
    have ht2 : (Multiplicative.toAdd g.2).val = 0 ∨ (Multiplicative.toAdd g.2).val = 1 := by
      have := ZMod.val_lt (Multiplicative.toAdd g.2); omega
    rcases hs2 with hs | hs <;> rcases ht2 with ht | ht
    · rw [Subgroup.mem_bot]
      have e1 : Multiplicative.toAdd g.1 = 0 := ZMod.val_injective (n := 2) (by rw [hs]; rfl)
      have e2 : Multiplicative.toAdd g.2 = 0 := ZMod.val_injective (n := 2) (by rw [ht]; rfl)
      apply Prod.ext
      · simpa using congrArg Multiplicative.ofAdd e1
      · simpa using congrArg Multiplicative.ofAdd e2
    · rw [hs, ht] at h0
      simp only [pow_zero, pow_one, Perm.one_apply, hbc0] at h0
      exact absurd h0 h02.symm
    · rw [hs, ht] at h0
      simp only [pow_zero, pow_one, Perm.one_apply, hac0] at h0
      exact absurd h0 h01.symm
    · rw [hs, ht] at h0
      simp only [pow_one, hbc0, hac2] at h0
      exact absurd h0 h03.symm
  have hφfix2 : ∀ (g : KleinG) (y : Fin n), φ g y ≠ y → y ∈ S := by
    intro g y hy; by_contra hc; exact hy (hφfix g y hc)
  have hφS : ∀ (g : KleinG) (y : Fin n), y ∈ S → φ g y ∈ S := by
    intro g y hy
    by_contra hns
    have h1 : φ g (φ g y) = φ g y := hφfix g (φ g y) hns
    have h2 : φ g y = y := (φ g).injective h1
    rw [h2] at hns; exact hns hy
  letI : MulAction KleinG (Perm (Fin n)) := MulAction.compHom (Perm (Fin n)) φ
  have hsmul : ∀ (g : KleinG) (σ : Perm (Fin n)), g • σ = φ g * σ := fun _ _ => rfl
  have hfree : ∀ σ : Perm (Fin n), MulAction.stabilizer KleinG σ = ⊥ := by
    intro σ
    rw [eq_bot_iff]; intro g hg
    rw [MulAction.mem_stabilizer_iff, hsmul] at hg
    rw [Subgroup.mem_bot]
    exact hφinj (by rw [map_one]; exact mul_right_cancel hg)
  have hcardG : Fintype.card KleinG = 4 := by decide
  have hspecial : ∀ y ∈ S, ∀ i : Fin n, (Nat.gcd ((y : ℕ) + 1) ((i : ℕ) + 1) : ZMod 4) = 1 := by
    intro y hy i
    simp only [hS, Finset.mem_insert, Finset.mem_singleton] at hy
    rcases hy with h|h|h|h <;> subst h <;>
      exact gcd_mod4_one _ _ (by simp only [v0,v1,v2,v3]; decide) (by simp only [v0,v1,v2,v3]; decide)
  have hginv : ∀ (g : KleinG) (y i : Fin n),
      (Nat.gcd ((φ g y : ℕ) + 1) ((i : ℕ) + 1) : ZMod 4)
        = (Nat.gcd ((y : ℕ) + 1) ((i : ℕ) + 1) : ZMod 4) := by
    intro g y i
    by_cases hyfix : φ g y = y
    · rw [hyfix]
    · have hyS : y ∈ S := hφfix2 g y hyfix
      rw [hspecial y hyS i, hspecial (φ g y) (hφS g y hyS) i]
  set f : Perm (Fin n) → ZMod (Fintype.card KleinG) :=
    fun σ => (((if Perm.sign σ = -1 then ∏ i, gcdMat n (σ i) i else 0 : ℤ)) : ZMod (Fintype.card KleinG))
    with hf_def
  have hf_inv : ∀ (g : KleinG) (σ : Perm (Fin n)), f (g • σ) = f σ := by
    intro g σ
    rw [hf_def, hsmul]
    have hsgnφ : Perm.sign (φ g) = 1 := by
      rw [hφ, MonoidHom.noncommCoprod_apply, map_mul, involHom_apply, involHom_apply,
        map_pow, map_pow, hsa, hsb, one_pow, one_pow, mul_one]
    have hsign : Perm.sign (φ g * σ) = Perm.sign σ := by rw [map_mul, hsgnφ, one_mul]
    simp only [hsign]
    by_cases hs : Perm.sign σ = -1
    · simp only [if_pos hs]
      push_cast
      apply Finset.prod_congr rfl
      intro i _
      simp only [Equiv.Perm.coe_mul, Function.comp_apply, gcdMat]
      push_cast
      exact hginv g (σ i) i
    · simp only [if_neg hs]
  have hsum : ∑ σ : Perm (Fin n), f σ = 0 :=
    sum_zmod_eq_zero_of_free_invariant hfree f hf_inv
  have hSig4 : (4 : ℤ) ∣ ∑ σ ∈ univ.filter (fun σ : Perm (Fin n) => Perm.sign σ = -1),
      ∏ i, gcdMat n (σ i) i := by
    have hz : (((∑ σ ∈ univ.filter (fun σ : Perm (Fin n) => Perm.sign σ = -1),
        ∏ i, gcdMat n (σ i) i : ℤ)) : ZMod (Fintype.card KleinG)) = 0 := by
      rw [← hsum, hf_def]
      push_cast
      rw [Finset.sum_filter]
    rw [ZMod.intCast_zmod_eq_zero_iff_dvd, hcardG] at hz
    exact_mod_cast hz
  have hid := permanent_sub_det (gcdMat n)
  obtain ⟨k, hk⟩ := hSig4
  obtain ⟨j, hj⟩ := eight_dvd_gcd_det n (by omega)
  refine ⟨j + k, ?_⟩
  have hpd : (gcdMat n).permanent = (gcdMat n).det + 2 *
      ∑ σ ∈ univ.filter (fun σ : Perm (Fin n) => Perm.sign σ = -1), ∏ i, gcdMat n (σ i) i := by
    linarith [hid]
  rw [hpd, hj, hk]; ring

end Paper3Four
